### ISSUE TITLE
Incorrect date set when in a 30 / 29 / 28 day month 

### ISSUE THREAD

**Issue by willrbc** [jfmdev/reactComboDatePicker#1]
When the current realtime month has less than 31 days you cannot choose the 31st day.

For example, it is now April. Trying to set the picker to 31st May returns 1st of May.

I have found this problem inside the `updateModel()` function.

```javascript
            this.model = new Date();
            this.model.setDate(date);
            this.model.setMonth(month);
            this.model.setFullYear(year);
```

Because it is currently April, `new Date()` returns a date in April.

The next line tries to set the day to 31st which is invalid, so the Date object reverts to the 1st.

A simple solution would be to set the day last

```javascript
            this.model = new Date();
            this.model.setMonth(month);
            this.model.setFullYear(year);
            this.model.setDate(date);
```

This would also allow you to set the 29th February in a leap year when you're currently in February of a non leap year.

**Comment by jfmdev** [comment]
Hi Will,

Thanks for reporting the bug, and sorry for the (very) late response.
The issue seems to be resolved (thanks to the solution you proposed) on version 1.0.1.

Regards
