### ISSUE TITLE
Select only months and years

### ISSUE THREAD

**Issue by chimeno** [jfmdev/reactComboDatePicker#2]
It would be great to be able to select only months and years, instead of the whole set (Day, Month, Year).

**Comment by jfmdev** [comment]
Hi Chimeno,

You can easily do that by using CSS and the `attrsDate` attribute, such as:

```jsx
ReactDOM.render(
    <ComboDatePicker date={new Date()} 
                     attrsDate={style: {display: 'none'}}/>,
    document.getElementById('container')
);
```

Regards
